version: '3'

services:
  mcp-terraform-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./examples:/app/examples
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 