version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./terraform:/app/terraform
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true 